# Generated by Django 5.1.7 on 2025-04-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=5000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sender_type", models.CharField(max_length=5)),
            ],
        ),
    ]
