# Generated by Django 5.1.8 on 2025-05-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatAI', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='sender_type',
            field=models.CharField(default='user', max_length=5),
        ),
    ]
